import db from "../index"

const locations = [
  {
    name: "Gendros Park",
    address1: "35 Gendros Avenue East",
    address2: null,
    city: "Swansea",
    county: "West Glamorgan",
    postCode: "Sa58df",
    poc: "Shaun David Hutch",
    contact: "5082430133",
  },
  {
    name: "Sennybridge Camp",
    address1: "High street (A40)",
    address2: null,
    city: "Becon",
    county: "Powys",
    postCode: "LD38PN",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Nesscliff Training Camp",
    address1: "National Cycle Rte 81",
    address2: "Wilcott",
    city: "Shrewsberry",
    county: "Shropshire",
    postCode: "SY41BH",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Swynnerton Camp",
    address1: "Meece Road",
    address2: null,
    city: "Stone",
    county: "Shropshire",
    postCode: "ST15 0QN",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Castlemartin (Merrion camp)",
    address1: "Castlemartin",
    address2: null,
    city: "Pembroke",
    county: "Pembrokeshire",
    postCode: "SA71 5EB",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Capel Curig Camp",
    address1: "Betws-yr-coed",
    address2: null,
    city: "Betws-yr-coed",
    county: "Conwy",
    postCode: "LL24 0DS",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Knook Camp",
    address1: "Knook",
    address2: null,
    city: "Warminster",
    county: "Wiltshire",
    postCode: " BA12 0JB",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Westdown Canp",
    address1: "Tilshead",
    address2: null,
    city: "Salisbury",
    county: "Wiltshire",
    postCode: " SP3 4RU",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Okehampton Camp",
    address1: "Camp road",
    address2: null,
    city: "Okehampton ",
    county: "Devon",
    postCode: "EX20 1QP ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Manobier Air Defence Range ",
    address1: "Manobier",
    address2: null,
    city: "Tenby",
    county: "Pembrokeshire ",
    postCode: "SA70 7SH",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Pembrey Sands",
    address1: "AWR",
    address2: null,
    city: "Pembrey",
    county: "Carmarthen ",
    postCode: "SA16 0HZ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Ballykinler Training Camp",
    address1: "30 Commons Road",
    address2: null,
    city: "Downpatrick",
    county: null,
    postCode: "BT30 8DQ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Magilligan Camp",
    address1: "95 Point Roag",
    address2: null,
    city: "Limavady",
    county: null,
    postCode: "BT49 0LP",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Kirkcudbright Camp",
    address1: "Camp Road",
    address2: null,
    city: "Kirkcudbright",
    county: null,
    postCode: "DG6 4QZ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Barry Buddon ",
    address1: "Carnoustie",
    address2: "Carnoustie",
    city: "Angus",
    county: null,
    postCode: "DD7 7RY",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Garelochhead Camp",
    address1: "Galelochhead TC",
    address2: null,
    city: "Helensburgh",
    county: null,
    postCode: "G84 0EH",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Kinlochleven Camp",
    address1: "Kinlochleven hostel",
    address2: null,
    city: "Kinlochleven ",
    county: null,
    postCode: "PH50 4SQ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Inverness Training Centre",
    address1: "Cameron Bks",
    address2: null,
    city: "Inverness ",
    county: null,
    postCode: "IV2 3XE",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Norwegian Lodge",
    address1: "N/A",
    address2: null,
    city: "Aviemore",
    county: null,
    postCode: "PH22 1QY",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Dundonnel AT Hut",
    address1: "Garve",
    address2: null,
    city: "Ross-Shirel",
    county: "N/A",
    postCode: "V23 2QR",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "CWTC",
    address1: "Faraid Head",
    address2: null,
    city: "Sutherland",
    county: "N/A",
    postCode: "IV27 4PZ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Tain AWR",
    address1: "Fendom ",
    address2: null,
    city: "Tain",
    county: "Ross-Shire",
    postCode: "IV19 1FG",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Westtofs Camp",
    address1: "Westtofs",
    address2: null,
    city: "Thetford",
    county: "Norfolk",
    postCode: "IP26 5EP",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Wreatham Camp",
    address1: "Westtofts",
    address2: null,
    city: "Thetford ",
    county: "Norfolk",
    postCode: "IP26 5EP",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Bodney Camp",
    address1: "Westtofs",
    address2: null,
    city: "Thetford ",
    county: "Norfolk ",
    postCode: "IP26 5EP",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Beckingham Camp",
    address1: "Woodgate lane ",
    address2: null,
    city: "Beckingham",
    county: "Lincolnshire ",
    postCode: "LN5 0RL",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "St Martins Plain",
    address1: "SMPC",
    address2: null,
    city: "Folkestone",
    county: "Kent",
    postCode: "CT20 3JG",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Longmoor Camp",
    address1: "Longmoor LISS",
    address2: null,
    city: "Longmoor",
    county: "Hampshire",
    postCode: "GU33 6EL",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Lydd Camp",
    address1: "Lydd",
    address2: null,
    city: "Rodney Marsh",
    county: null,
    postCode: "TN29 9JR",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Brunswick Camp",
    address1: "Alexander Bks",
    address2: null,
    city: "Woking ",
    county: "Surrey",
    postCode: "GU24 0QQ",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Crowborough Camp",
    address1: "The warren",
    address2: null,
    city: "Crowborough",
    county: null,
    postCode: "TN6 1UB",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Otterburn Camp",
    address1: "Otterburn",
    address2: null,
    city: "Otterburn",
    county: "Northumberland ",
    postCode: "NE191HT",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Warcop Camp",
    address1: "Appleby",
    address2: null,
    city: "Appleby",
    county: "Cumbria ",
    postCode: "CA16 6PA",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Ambleside",
    address1: "Halton Camp",
    address2: null,
    city: "Halton",
    county: "Lancaster ",
    postCode: "LA2 6LW",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Wathgill Camp",
    address1: "Downholme",
    address2: null,
    city: "Richmond",
    county: "North Yorkshire ",
    postCode: "DL11 6AH",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Halton Camp",
    address1: "N/A",
    address2: null,
    city: "Lancaster ",
    county: null,
    postCode: "LA2 6LW",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Willsworthy Camp",
    address1: "N/A",
    address2: null,
    city: "N/A",
    county: "Dartmoor ",
    postCode: "EX20 4AL",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Rollestone Camp",
    address1: "N/A",
    address2: null,
    city: "Salisbury",
    county: "Wiltshire",
    postCode: "SP3 4DS",
    poc: "TBC",
    contact: "TBC",
  },
  {
    name: "Chickerell Camp",
    address1: "Wyke Regis ",
    address2: null,
    city: "Weymouth ",
    county: "Norfolk",
    postCode: "DT4 9HH",
    poc: "TBC",
    contact: "TBC",
  },
]

const createLocations = () => {
  db.location.deleteMany({})

  locations.forEach(async (location) => {
    await db.location.create({
      data: {
        ...location,
      },
    })
  })
}

export default createLocations
