-- CreateTable
CREATE TABLE "Day" (
    "id" INTEGER NOT NULL,
    "date_dim_id" INTEGER NOT NULL,
    "date_actual" TIMESTAMP(3) NOT NULL,
    "epoch" BIGINT NOT NULL,
    "day_suffix" VARCHAR(4) NOT NULL,
    "day_name" VARCHAR(9) NOT NULL,
    "day_of_week" INTEGER NOT NULL,
    "day_of_month" INTEGER NOT NULL,
    "day_of_quarter" INTEGER NOT NULL,
    "day_of_year" INTEGER NOT NULL,
    "week_of_month" INTEGER NOT NULL,
    "week_of_year" INTEGER NOT NULL,
    "week_of_year_iso" CHAR(10) NOT NULL,
    "month_actual" INTEGER NOT NULL,
    "month_name" VARCHAR(9) NOT NULL,
    "month_name_abbreviated" CHAR(3) NOT NULL,
    "quarter_actual" INTEGER NOT NULL,
    "quarter_name" VARCHAR(9) NOT NULL,
    "year_actual" INTEGER NOT NULL,
    "first_day_of_week" TIMESTAMP(3) NOT NULL,
    "last_day_of_week" TIMESTAMP(3) NOT NULL,
    "first_day_of_month" TIMESTAMP(3) NOT NULL,
    "last_day_of_month" TIMESTAMP(3) NOT NULL,
    "first_day_of_quarter" TIMESTAMP(3) NOT NULL,
    "last_day_of_quarter" TIMESTAMP(3) NOT NULL,
    "first_day_of_year" TIMESTAMP(3) NOT NULL,
    "last_day_of_year" TIMESTAMP(3) NOT NULL,
    "mmyyyy" CHAR(6) NOT NULL,
    "mmddyyyy" CHAR(10) NOT NULL,
    "weekend_indr" BOOLEAN NOT NULL,

    CONSTRAINT "Day_pkey" PRIMARY KEY ("id")
);
